export const mimeTypes = {
  ".pdf": "PDFs",
  ".docx": "Word Files",
  ".jpeg": "Images",
  ".webp": "Images",
  ".jpg": "Images",
  ".png": "Images",
  ".svg": "Images",
  ".gif": "Images",
  ".mp4": "Videos",
  ".mkv": "Videos",
  ".avi": "Videos",
  ".mov": "Videos",
  ".mp3": "Audios",
  ".wav": "Audios",
  ".aac": "Audios",
  ".flac": "Audios",
  ".zip": "Compressed Archives",
  ".rar": "Compressed Archives",
  ".7z": "Compressed Archives",
  ".exe": "Applications",
  ".json": "JSON Files",
  ".csv": "CSV Files",
  ".rmskin": "Rainmeter Skin Packagers",
  ".lit": "eBooks",
  ".fb2": "eBooks",
  ".epub": "eBooks",
  ".mobi": "eBooks",
  ".azw3": "eBooks",
  ".xlsx": "Spreadsheets",
  ".xls": "Spreadsheets",
  ".xlsm": "Spreadsheets",
  ".md": "Text Files",
  ".txt": "Text Files",
  ".pptx": "Presentations",
  ".ppt": "Presentations",
  ".odp": "Presentations",
  ".pptm": "Presentations",
  ".html": "HTML Files",
  ".py": "Programming Source Files",
  ".c": "Programming Source Files",
  ".cpp": "Programming Source Files",
  ".cc": "Programming Source Files",
  ".cs": "Programming Source Files",
  ".js": "Programming Source Files",
  ".ts": "Programming Source Files",
  ".tsx": "Programming Source Files",
  ".jsx": "Programming Source Files",
  ".java": "Programming Source Files",
  ".ipynb": "Jupyter Notebook Files",
  ".sql": "Database Files",
  ".db": "Database Files",
  ".msi": "Installers",
  ".psd": "Photoshop Documents",
  ".slx": "Engineering & Scientific Projects",
  ".mat": "Engineering & Scientific Projects",
  ".m": "Engineering & Scientific Projects",
  ".fig": "Engineering & Scientific Projects",
  ".ini": "Configuration Files",
  ".iso": "Disk Images",
  ".torrent": "Torrent Files",
  ".apk": "Android Packages",
};
